services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/workdir
    ports:
      - 3010:3000
  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - 8001:8001
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.3
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: django_db
    ports:
      - 3306:3306
    healthcheck:
      # mysqlが起動してからbackendを起動する
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      # 10秒とに生きてるか確認する
      interval: 10s
      # 5秒以内に応答がなければ失敗
      timeout: 5s
      # 5回失敗したら停止する
      retries: 5
      # 起動後40秒間は無視する
      start_period: 40s
